version: "3.4"

services:

  app:
    image: otus-microservice-architecture-app
    container_name: otus-microservice-architecture-app
    build:
      context: .
      target: app
      args:
        - GOLANG_VERSION
    ports:
      - "8000:${PORT}"
    env_file:
      - .env
    volumes:
      - "./:/app"
    working_dir: "/app"
    command: ["application"]
    restart: unless-stopped
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:${PORT}/healthcheck || exit 1
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s
    networks:
      otus-microservice-architecture:
        aliases:
          - app

networks:
  otus-microservice-architecture:
