{
 "title": "Otus App",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Product list",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(http_request_duration_seconds_bucket{method=\"product_list\"}[1m])) by (le))",
     "legendFormat": "90th"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{method=\"product_list\"}[1m])) by (le))",
     "legendFormat": "95th"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket{method=\"product_list\"}[1m])) by (le))",
     "legendFormat": "99th"
    },
    {
     "expr": "histogram_quantile(1, sum(rate(http_request_duration_seconds_bucket{method=\"product_list\"}[1m])) by (le))",
     "legendFormat": "100th"
    },
    {
     "expr": "sum(rate(http_request_duration_seconds_count{method=\"product_list\"}[1m])) * 60",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "Errors 5xx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(increase(http_requests_total{code=~\"5[0-9]{2}\"}[$__range])) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "5XX Errors",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_requests_total{code=~\"5[0-9]{2}\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "App Errors",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(app_errors)", "legendFormat": "__auto" }
   ]
  }
 ]
}