// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0

package db

import (
	"database/sql"
)

type Product struct {
	ID              int64          `db:"id" json:"id"`
	Name            string         `db:"name" json:"name"`
	Article         string         `db:"article" json:"article"`
	Brand           string         `db:"brand" json:"brand"`
	CountryOfOrigin string         `db:"country_of_origin" json:"country_of_origin"`
	Description     sql.NullString `db:"description" json:"description"`
	Price           string         `db:"price" json:"price"`
	Rating          string         `db:"rating" json:"rating"`
	VoteCount       int32          `db:"vote_count" json:"vote_count"`
	VoteSum         int32          `db:"vote_sum" json:"vote_sum"`
}
