apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-env-app
  annotations:
    releaseRevision: "{{ .Release.Revision }}"
data:
  PORT: "80"
  DEBUG: "false"
  DB_HOST: "otus-microservice-architecture-postgresql"
  DB_PORT: "5432"
  DB_DATABASE: "otus-microservice-architecture"
  DB_DRIVER: "postgres"
  DB_MAX_IDLE_CONNS: "2"
  DB_MAX_IDLE_CONN_TIME: "5m"
  DB_MAX_CONNS: "20"
  DB_CONN_MAX_LIFETIME: "10m"
  AUTH_TOKEN_TTL: "10m"
  AUTH_JWT_SECRET_KEY: "some_jwt_secret"
