apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "otus-microservice-architecture.fullname" . }}-migrate
  labels:
    app: {{ include "otus-microservice-architecture.fullname" . }}-migrate
    release: {{ .Release.Name }}
spec:
  template:
    metadata:
      name: {{ include "otus-microservice-architecture.fullname" . }}-migrate
    spec:
      restartPolicy: Never
      initContainers:
        - name: {{ .Chart.Name }}-check-ready-postgresql
          image: "{{ .Values.postgresql.image.repository }}:{{ .Values.postgresql.image.tag }}"
          imagePullPolicy: {{ .Values.postgresql.image.pullPolicy }}
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret-app
                  key: DB_USER
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-env-app
          command:
            - "sh"
            - "-c"
            - |
              until pg_isready -d $DB_DATABASE -U $DB_USER -h $DB_HOST  -p $DB_PORT;
              do echo waiting for database; sleep 2; done;
      containers:
        - name: {{ .Chart.Name }}-migrate-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          args: ["migrate"]
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.secret.enabled }}
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret-app
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret-app
                  key: DB_PASSWORD
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-env-app