apiVersion: v1
kind: Service
metadata:
  name: {{ include "otus-microservice-architecture.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "otus-microservice-architecture.labels" . | nindent 4 }}
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ include "otus-microservice-architecture.fullname" . }}-app
