apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "otus-microservice-architecture.serviceAccountName" . }}-postgresql
  labels:
    {{- include "otus-microservice-architecture.labels" . | nindent 4 }}
    release: {{ .Release.Name }}
