apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "otus-microservice-architecture.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
    - "*"
  gateways:
    - {{ include "otus-microservice-architecture.fullname" . }}
  http:
    - route:
        - destination:
            subset: v1
            host: {{ include "otus-microservice-architecture.fullname" . }}
            port:
              number: 80
          weight: 50
        - destination:
            subset: v2
            host: {{ include "otus-microservice-architecture.fullname" . }}
            port:
              number: 80
          weight: 50