// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package responses

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson5c9a64eeDecodeOtusMicroserviceArchitectureAppApiResponses(in *jlexer.Lexer, out *ProductGetOkResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = int64(in.Int64())
		case "name":
			out.Name = string(in.String())
		case "article":
			out.Article = string(in.String())
		case "brand":
			out.Brand = string(in.String())
		case "country_of_origin":
			out.CountryOfOrigin = string(in.String())
		case "description":
			out.Description = string(in.String())
		case "price":
			out.Price = string(in.String())
		case "rating":
			out.Rating = string(in.String())
		case "version":
			out.Version = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson5c9a64eeEncodeOtusMicroserviceArchitectureAppApiResponses(out *jwriter.Writer, in ProductGetOkResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.ID))
	}
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"article\":"
		out.RawString(prefix)
		out.String(string(in.Article))
	}
	{
		const prefix string = ",\"brand\":"
		out.RawString(prefix)
		out.String(string(in.Brand))
	}
	{
		const prefix string = ",\"country_of_origin\":"
		out.RawString(prefix)
		out.String(string(in.CountryOfOrigin))
	}
	{
		const prefix string = ",\"description\":"
		out.RawString(prefix)
		out.String(string(in.Description))
	}
	{
		const prefix string = ",\"price\":"
		out.RawString(prefix)
		out.String(string(in.Price))
	}
	{
		const prefix string = ",\"rating\":"
		out.RawString(prefix)
		out.String(string(in.Rating))
	}
	{
		const prefix string = ",\"version\":"
		out.RawString(prefix)
		out.String(string(in.Version))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ProductGetOkResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson5c9a64eeEncodeOtusMicroserviceArchitectureAppApiResponses(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ProductGetOkResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson5c9a64eeEncodeOtusMicroserviceArchitectureAppApiResponses(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ProductGetOkResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson5c9a64eeDecodeOtusMicroserviceArchitectureAppApiResponses(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ProductGetOkResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson5c9a64eeDecodeOtusMicroserviceArchitectureAppApiResponses(l, v)
}
